databases:
  - name: magicdb
    plan: free
    databaseName: magic
    user: magic

services:
  - type: web
    plan: free
    name: magic
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn MagicGathering.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: magicdb
          property: connectionString
      - key: SETTINGS_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4