# Generated by Django 5.0.4 on 2024-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccard',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
