# Generated by Django 5.0.4 on 2024-05-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_magiccard_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiccard',
            name='set_name',
            field=models.CharField(default='test', max_length=225),
            preserve_default=False,
        ),
    ]
