# Generated by Django 5.0.4 on 2024-05-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_magiccard_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('cards', models.ManyToManyField(to='cards.magiccard')),
            ],
        ),
    ]
